export default [
  {
    name: 'title',
    title: 'Title',
    type: 'string',
    readOnly: true,
    fieldset: 'shopify',
  },
  {
    name: 'id',
    title: 'ID',
    type: 'string',
    readOnly: true,
    hidden: true,
    fieldset: 'shopify',
  },
  {
    name: 'deleted',
    title: 'Deleted',
    type: 'boolean',
    readOnly: true,
    fieldset: 'shopify',
  },
  {
    name: 'image',
    type: 'image',
    title: 'Shopify Image',
    readOnly: true,
    fieldset: 'shopify',
  },
  {
    name: 'productId',
    title: 'Product ID',
    type: 'number',
    readOnly: true,
    hidden: true,
    fieldset: 'shopify',
  },
  {
    name: 'defaultPrice',
    title: 'Default Price',
    type: 'string',
    readOnly: true,
    fieldset: 'shopify',
  },
  {
    name: 'variants',
    title: 'Variants',
    type: 'array',
    of: [{type: 'reference', to: {type: 'variant'}}],
    readOnly: true,
    fieldset: 'shopify',
  },
];
