export default [
  {
    name: 'variantTitle',
    title: 'Variant Title',
    type: 'string',
    readOnly: true,
    fieldset: 'shopify',
  },
  {
    title: 'Default Variant',
    name: 'default',
    readOnly: true,
    type: 'boolean',
    fieldset: 'shopify',
  },
  {
    name: 'productId',
    title: 'Product ID',
    type: 'number',
    description: 'This comes from Shopify and cannot be changed',
    readOnly: true,
    hidden: true,
    fieldset: 'shopify',
  },
  {
    name: 'variantId',
    title: 'Variant ID',
    type: 'number',
    description: 'This comes from Shopify and cannot be changed',
    readOnly: true,
    hidden: true,
    fieldset: 'shopify',
  },
  {
    title: 'Weight in grams',
    name: 'grams',
    readOnly: true,
    type: 'number',
    fieldset: 'shopify',
  },
  {
    title: 'Price',
    name: 'price',
    readOnly: true,
    type: 'string',
    fieldset: 'shopify',
  },
  {
    title: 'SKU',
    name: 'sku',
    readOnly: true,
    type: 'string',
    fieldset: 'shopify',
  },
  {
    title: 'Taxable',
    name: 'taxable',
    readOnly: true,
    type: 'boolean',
    fieldset: 'shopify',
  },
  {
    title: 'Inventory Policy',
    name: 'inventoryPolicy',
    readOnly: true,
    type: 'string',
    fieldset: 'shopify',
  },
  {
    title: 'Inventory Quantity',
    name: 'inventoryQuantity',
    readOnly: true,
    type: 'number',
    fieldset: 'shopify',
  },
  {
    title: 'Bar code',
    name: 'barcode',
    readOnly: true,
    type: 'string',
    fieldset: 'shopify',
  },
];
